# Generated by Django 2.0.6 on 2019-10-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='Zipcode', max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, db_column='TelePhone', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('writer', models.CharField(blank=True, db_column='Writer', max_length=255, null=True)),
                ('publish', models.CharField(blank=True, db_column='Publish', max_length=255, null=True)),
                ('publish_time', models.DateField(blank=True, db_column='Publish_time', null=True)),
                ('version', models.IntegerField(blank=True, db_column='Version', null=True)),
                ('book_isbn', models.CharField(blank=True, db_column='Book_ISBN', max_length=255, null=True)),
                ('words', models.IntegerField(blank=True, db_column='Words', null=True)),
                ('pages', models.IntegerField(blank=True, db_column='Pages', null=True)),
                ('book_size', models.IntegerField(blank=True, db_column='Book_size', null=True)),
                ('paper', models.CharField(blank=True, db_column='Paper', max_length=255, null=True)),
                ('pack', models.CharField(blank=True, db_column='Pack', max_length=255, null=True)),
                ('category_0', models.CharField(blank=True, db_column='Category', max_length=255, null=True)),
                ('first_price', models.FloatField(blank=True, db_column='First_price', null=True)),
                ('last_price', models.FloatField(blank=True, db_column='Last_price', null=True)),
                ('editor_commend', models.TextField(blank=True, db_column='Editor_Commend', null=True)),
                ('content_introduction', models.TextField(blank=True, db_column='Content_introduction', null=True)),
                ('writer_introduction', models.TextField(blank=True, db_column='Writer_introduction', null=True)),
                ('catalogs', models.TextField(blank=True, db_column='Catalogs', null=True)),
                ('media_comment', models.TextField(blank=True, db_column='Media_comment', null=True)),
                ('picture', models.CharField(blank=True, db_column='Picture', max_length=255, null=True)),
                ('product_image', models.CharField(blank=True, db_column='Product_image', max_length=255, null=True)),
                ('series_name', models.CharField(blank=True, db_column='Series_name', max_length=255, null=True)),
                ('print_time', models.DateField(blank=True, db_column='Print_time', null=True)),
                ('impression', models.CharField(blank=True, db_column='Impression', max_length=255, null=True)),
                ('stock', models.IntegerField(blank=True, db_column='Stock', null=True)),
                ('shelves_date', models.DateField(blank=True, db_column='Shelves_date', null=True)),
                ('score', models.DecimalField(blank=True, db_column='Score', decimal_places=2, max_digits=3, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('sales', models.IntegerField(blank=True, db_column='Sales', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('order_id', models.AutoField(db_column='Order_id', primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(blank=True, db_column='Create_date', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_num', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, db_column='Total_price', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_orders',
            },
        ),
        migrations.CreateModel(
            name='TShop',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('booknum', models.IntegerField(blank=True, db_column='BookNum', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_shop',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email_address', models.CharField(blank=True, db_column='Email_Address', max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, db_column='NickName', max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('method', models.CharField(blank=True, db_column='Method', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_user',
            },
        ),
    ]
